# Generated by Django 3.1.8 on 2023-10-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=50)),
                ('boodetails', models.CharField(max_length=100)),
                ('bookauthor', models.CharField(max_length=50)),
                ('bookimage', models.ImageField(upload_to='images/')),
                ('bookpath', models.FileField(upload_to='book_path/')),
            ],
        ),
    ]
